-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAYzzyjSk/QASWs+2
BOEQi/QBEs0j4B39B+9jUZp3QWWgCgYIKoZIzj0DAQehRANCAAT3sbpEOFZIASG1
BbyGHOWCchOxdcXv4b8P9LZL1tlzoffenDJN9gjiLOQ5ynYzlaaLaDcKzQqwUssr
MgpAuspO
-----END PRIVATE KEY-----